# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

import wizlad.draw

# Load existing settings made via :set
config.load_autoconfig()

wizlad.draw.blood(c, {
	'spacing': {
		'vertical': 6,
  	'horizontal': 8
  }
})


