#!/usr/bin/env bash

if [[ $(echo $OSTYPE|grep 'darwin') ]]; then 
	chmod +x ./mac/install 
	./mac/install 
elif [[ $(uname -a|grep 'ubuntu') ]]; then
	chmod +x ./ubuntu/install
	./ubuntu/install
fi 

chmod +x ./zsh/install
./zsh/install

# If no projects folder in home exists; make one
if [[ ! -d ~/Projects ]]; then mkdir ~/Projects; fi
