#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Bjarke Brodin <bjarke@brodin.dk>

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# dotnet tools
export PATH="$PATH:$HOME/.dotnet/tools/"

# classpath appendices
export CLASSPATH="$CLASSPATH:/Library/Jar/"