#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.aliases
source ~/.functions

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/bjarkebrodin/.sdkman"
[[ -s "/Users/bjarkebrodin/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/bjarkebrodin/.sdkman/bin/sdkman-init.sh"
