#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -vH

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

chmod +x mac/install_homebrew
./mac/install_homebrew

if [[ ! $(brew -v) ]] 
then 
        echo 'Homebrew not installed, exiting!'
        echo 'Try installing homebrew manually, and rerun'
        exit
fi

brew update
brew upgrade

# More recent versions of some macOS tools.
brew install vim 
brew install grep
brew install openssh
brew install screen
brew install php
brew install gmp

# `wget` with IRI support.
brew install wget 

# Misc utils
brew install coreutils
brew install moreutils
brew install findutils
brew install gnu-sed 
brew install tree
brew install python
brew install lynx
brew install lua
brew install fd
brew install ripgrep
brew install tldr
brew install node

# Update pip
sudo -H pip3 install --upgrade pip

# Ranger
sudo -H pip3 install ranger-fm

# Spectacle
brew cask install spectacle

# Spotify
brew cask install spotify

# Google Chrome
brew cask install google-chrome

# Figma
brew cask install figma

# iTerm2
brew cask install iterm2

# Fonts 
brew tap homebrew/cask-fonts
brew cask install font-fira-code

# Sass
npm install -g sass

# VSCode
brew cask install visual-studio-code

# IntelliJ IDEA Ultimate
brew cask install intellij-idea

# Clion
brew cask install clion

# Visual Studio
brew cask install visual-studio

# Latex
brew cask install mactex-no-gui

# Alacritty
brew cask install alacritty
