filetype plugin indent on

" show relative line numbering
set relativenumber

" remove annoying bell
set vb
set t_vb=

" stop vim from creating swapfiles everywhere
set noswapfile

" use global clipboard
set clipboard=unnamed
