#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Alt left/right moves words
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# Alt up/down goes to beggining/end of line
bindkey "^[[1;3A" beginning-of-line
bindkey "^[[1;3B" end-of-line

# Enable vim mode
bindkey -v

# Source Aliases
source ~/.aliases
