#!/usr/bin/env zsh

# Clone prezto files to home or zdot
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Remove any existing zshrc and symlink prezto
if [[ -f ~/.zshrc ]]; then rm ~/.zshrc; fi
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

chmod +x ./zsh/apply
./zsh/apply
