#!/usr/bin/env bash

if [[ $(uname -a|grep 'ubuntu') ]]; then
	sudo apt-get install zsh
fi

# Clone prezto files to home or zdot
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

chmod +x ./zsh/apply
./zsh/apply
